### ISSUE TITLE
Support chunk id in storage path

### ISSUE THREAD

**Issue by songjiaxun** [elsesiy/fluent-plugin-azure-storage-append-blob-lts#6]
Currently, we are passing `Metadata` instead of `Chunk` to function `extract_placeholders`.
https://github.com/elsesiy/fluent-plugin-azure-storage-append-blob-lts/blob/eb39f3c51a5b533969968a4d38df2cc2e4394bd1/lib/fluent/plugin/out_azure-storage-append-blob.rb#L231

This prevents users from using chunk_id as a part of the output path. You will get this error message if you pass `${chunk_id}` to `azure_object_key_format`: 

`[warn]: #0 ${chunk_id} is not allowed in this plugin. Pass Chunk instead of metadata in extract_placeholders's 2nd argument.`

**Comment by elsesiy** [comment]
Fixed via #7, new version `0.6.2` has been released
